language: csharp
solution: Proxy.sln
mono:
  - latest

# dotnet: 4.6.1

# install:
#   - nuget restore Proxy.sln
#   - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Release Proxy.sln
#   - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll